### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'DazFingerPrint' on Blender 5.2

### ISSUE THREAD

**Issue by kdansingani** [Diffeomorphic/import_daz#81]
Blender version: 5.2.0
Addon commit: d0ce33dd81add736fb5149ef28c6ccba5336da53 (current master)

Error:

AttributeError: 'Mesh' object has no attribute 'DazFingerPrint'

Traceback (most recent call last):
  ...
  File "...\geometry.py", line 1393, in buildData
    guideMe.DazFingerPrint = getFingerPrint(guideOb)
AttributeError: 'Mesh' object has no attribute 'DazFingerPrint'

Steps to reproduce:
1. Perform an Easy Import of a DAZ figure.
2. The import fails during mesh construction.

Notes according to AI debugging:
- The import worked fine a few days ago.
- The bug was probably introduced in commit d0ce33dd ("Fix for issue 73: No sharp edges for geografts.").
- Almost all other references to DazFingerPrint in the addon correctly use the dazRna() wrapper, but this one line still performs a direct attribute assignment on the Mesh datablock.
- Blender 5.2 appears to enforce stricter rules around direct attribute assignment on mesh data compared to earlier versions.

Suggested fix:
Change line 1393 in geometry.py from:
python
guideMe.DazFingerPrint = getFingerPrint(guideOb)

to:
python
dazRna(guideMe).DazFingerPrint = getFingerPrint(guideOb)

**Comment by Diffeomorphic** [comment]
Fixed in last commit. The issue only arises if you import strand-based hair and the global setting "Build all hair versions" is enabled.
