### ISSUE TITLE
Regression in 1abc6815: TypeError in getFingeredCharacters – addChar() missing required argument

### ISSUE THREAD

**Issue by kdansingani** [Diffeomorphic/import_daz#86]
AI-assisted debug

Blender version: 5.2
Addon commit: 1abc6815

Error:
TypeError: getFingeredCharacters.<locals>.addChar() missing 1 required positional argument: 'mesh'

Location:
finger.py, line 203 (inside getFingeredCharacters):

python
addChar(dazRna(child.data).DazFingerPrint, child)

Notes:
- The inner function was changed to addChar(finger, rig, mesh), but this call site only passes two arguments.
- Occurs during Easy Import when loading standard morphs (getFingeredRigMeshes).
- This is a regression introduced in the same commit that fixed issue #81.

Suggested fix:
python
addChar(dazRna(child.data).DazFingerPrint, ob, child)

**Comment by Diffeomorphic** [comment]
Fixed in last commit. Sorry.
